/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running app and checked in here so the
// workspace typecheck has the expected framework ambient types.
